steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/crypto-planet-415008/github.com/themadbrains18/nextjs-google-cloud:e05efec359dc2805319baeac27b6d8ef48e96926', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/crypto-planet-415008/github.com/themadbrains18/nextjs-google-cloud:e05efec359dc2805319baeac27b6d8ef48e96926']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'SERVICE-NAME', '--image', 'gcr.io/crypto-planet-415008/github.com/themadbrains18/nextjs-google-cloud:e05efec359dc2805319baeac27b6d8ef48e96926', '--region', 'us-central1']
images:
- gcr.io/crypto-planet-415008/github.com/themadbrains18/nextjs-google-cloud:e05efec359dc2805319baeac27b6d8ef48e96926